#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v26
# autospec commit: 99a7985
#
Name     : R-zeallot
Version  : 0.2.0
Release  : 40
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/zeallot_0.2.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/zeallot_0.2.0.tar.gz
Summary  : Multiple, Unpacking, and Destructuring Assignment
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
unpacking, and destructuring assignment in R. The
    operator unpacks the right-hand side of an assignment
    into multiple values and assigns these values to
    variables on the left-hand side of the assignment.

%prep
%setup -q -n zeallot
pushd ..
cp -a zeallot buildavx2
popd
pushd ..
cp -a zeallot buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1748375733

%install
export SOURCE_DATE_EPOCH=1748375733
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/zeallot/DESCRIPTION
/usr/lib64/R/library/zeallot/INDEX
/usr/lib64/R/library/zeallot/LICENSE
/usr/lib64/R/library/zeallot/Meta/Rd.rds
/usr/lib64/R/library/zeallot/Meta/features.rds
/usr/lib64/R/library/zeallot/Meta/hsearch.rds
/usr/lib64/R/library/zeallot/Meta/links.rds
/usr/lib64/R/library/zeallot/Meta/nsInfo.rds
/usr/lib64/R/library/zeallot/Meta/package.rds
/usr/lib64/R/library/zeallot/Meta/vignette.rds
/usr/lib64/R/library/zeallot/NAMESPACE
/usr/lib64/R/library/zeallot/NEWS.md
/usr/lib64/R/library/zeallot/R/zeallot
/usr/lib64/R/library/zeallot/R/zeallot.rdb
/usr/lib64/R/library/zeallot/R/zeallot.rdx
/usr/lib64/R/library/zeallot/doc/index.html
/usr/lib64/R/library/zeallot/doc/unpacking-assignment.R
/usr/lib64/R/library/zeallot/doc/unpacking-assignment.Rmd
/usr/lib64/R/library/zeallot/doc/unpacking-assignment.html
/usr/lib64/R/library/zeallot/help/AnIndex
/usr/lib64/R/library/zeallot/help/aliases.rds
/usr/lib64/R/library/zeallot/help/paths.rds
/usr/lib64/R/library/zeallot/help/zeallot.rdb
/usr/lib64/R/library/zeallot/help/zeallot.rdx
/usr/lib64/R/library/zeallot/html/00Index.html
/usr/lib64/R/library/zeallot/html/R.css
/usr/lib64/R/library/zeallot/tests/testthat.R
/usr/lib64/R/library/zeallot/tests/testthat/test-collectors.R
/usr/lib64/R/library/zeallot/tests/testthat/test-destructure.R
/usr/lib64/R/library/zeallot/tests/testthat/test-error-handling.R
/usr/lib64/R/library/zeallot/tests/testthat/test-operator.R
/usr/lib64/R/library/zeallot/tests/testthat/test-pipe.R
/usr/lib64/R/library/zeallot/tests/testthat/test-utils.R
/usr/lib64/R/library/zeallot/tests/testthat/test-zeallous.R
